apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    # cert-manager will handle certificate
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # NGINX SSL configuration
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Backend protocol (ArgoCD uses HTTP on port 80)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # IP whitelist
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.20.0.0/24,192.168.1.0/24,10.8.0.0/24,10.43.0.0/24,45.127.123.126/32"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.hikmahtech.in
    secretName: argocd-tls  # cert-manager will create this secret
  rules:
    - host: argocd.hikmahtech.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80