# Homarr database encryption secret
# Required for Homarr v1.x with PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: db-encryption
  namespace: homelab
type: Opaque
stringData:
  db-encryption-key: "797ab222bdfbc78e63e8a10cb944ecec7741b8d54242565cf7ad07185cb5554c"
