---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    # cert-manager will handle certificate
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # NGINX SSL configuration
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # IP whitelist
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.20.0.0/24,192.168.1.0/24,10.8.0.0/24,10.43.0.0/24,45.127.123.126/32"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grafana.hikmahtech.in
    secretName: grafana-tls
  rules:
    - host: grafana.hikmahtech.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-stack-grafana
                port:
                  number: 80