---
# Handlers for CasaOS role

- name: restart jellyfin
  systemd:
    name: jellyfin-container
    state: restarted
    daemon_reload: true
  become: true

- name: restart qbittorrent
  systemd:
    name: qbittorrent-container
    state: restarted
    daemon_reload: true
  become: true

- name: restart casaos
  systemd:
    name: casaos
    state: restarted
  become: true