apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-metrics
  namespace: postgres
  labels:
    app: postgres
    release: prometheus-stack  # Important: Must match Prometheus operator selector
spec:
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: hikmah-db
      postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
  podMetricsEndpoints:
  - port: exporter
    interval: 30s
    path: /metrics
    scheme: http