# MinIO S3 Credentials for Loki
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-secret
  namespace: loki
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: Jamil@123
  AWS_REGION: us-east-1
